# Generated by Django 2.1.10 on 2020-01-13 14:03

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('filetype', models.CharField(max_length=20)),
                ('sourceid', models.IntegerField(null=True)),
                ('capture', models.DateTimeField(null=True)),
                ('altitude', models.FloatField(default=0)),
                ('roll', models.FloatField(default=0)),
                ('pitch', models.FloatField(default=0)),
                ('pan', models.FloatField(default=0)),
                ('geom', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Panorama',
                'verbose_name_plural': 'Panoramas',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'Panorama',
                'verbose_name_plural': 'Panoramas',
            },
        ),
        migrations.AddField(
            model_name='panorama',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='mapia_panoramas.Project', to_field='code'),
        ),
    ]
