# Generated by Django 2.1.5 on 2020-12-04 09:09

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapia_panoramas', '0002_auto_20200415_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lateral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('file_folder', models.CharField(blank=True, max_length=100, null=True)),
                ('file_type', models.CharField(blank=True, max_length=20, null=True)),
                ('pan', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Lateral image',
                'verbose_name_plural': 'Lateral images',
            },
        ),
        migrations.CreateModel(
            name='PointCloud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('file_folder', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(db_index=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Point cloud',
                'verbose_name_plural': 'Point clouds',
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.RenameField(
            model_name='panorama',
            old_name='capture',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='panorama',
            old_name='filename',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='panorama',
            old_name='sourceid',
            new_name='source_id',
        ),
        migrations.RemoveField(
            model_name='panorama',
            name='filetype',
        ),
        migrations.AddField(
            model_name='panorama',
            name='file_folder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='panorama',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='folder_images',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='folder_panorama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='folder_point_cloud',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pointcloud',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapia_panoramas.Project'),
        ),
        migrations.AddField(
            model_name='lateral',
            name='panorama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapia_panoramas.Panorama'),
        ),
    ]
