# Generated by Django 2.1.5 on 2020-12-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapia_panoramas', '0003_auto_20201204_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panorama',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
