# Generated by Django 2.1.5 on 2020-12-04 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapia_panoramas', '0004_auto_20201204_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lateral',
            name='panorama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laterals', to='mapia_panoramas.Panorama'),
        ),
    ]
