# Generated by Django 2.1.5 on 2020-12-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapia_panoramas', '0005_auto_20201204_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='layer_panorama',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
