# Generated by Django 2.1.5 on 2021-01-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapia_panoramas', '0009_localpointcloud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panorama',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='panorama',
            name='source_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
