# Generated by Django 2.2.20 on 2022-04-28 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapia_panoramas', '0010_auto_20210119_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointcloud',
            name='project',
        ),
    ]
