# Generated by Django 2.2.20 on 2022-04-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapia_panoramas', '0011_remove_pointcloud_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointcloud',
            name='project',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mapia_panoramas.Project', to_field='code'),
            preserve_default=False,
        ),
    ]
